### ISSUE TITLE
deserialization problem in RTS

### ISSUE THREAD

**Issue by jedirv** [SCAII/Sky-RTS#12]
I've confirmed that the Replay is emitting exactly the same SerializationResponse as what was recorded , so the deserialization problem must be in the RTS. 

To replicate, 
-pull integ versions of both RTS and SCAII.  
-build both in debug mode and copy the binaries into play.
-cd into .scaii/git/Sky-RTS/demos and change record_agent to do one rather than 2 episodes.
- run record_agent

this will generate the default replay file under .scaii/replays

- then cd into .scaii/git/SCAII/core
- cargo run webserver
- in another cmd shell, cd into .scaii/git/SCAII/cargo
- cargo run file

Here is the error:  
```
thread '<unnamed>' panicked at 'Already borrowed: InvalidBorrow', src\libcore\result.rs:916:5
stack backtrace:
   0: std::sys::windows::backtrace::unwind_backtrace
             at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:65
   1: std::sys_common::backtrace::print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:56
   2: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:381
   3: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:577
   5: std::panicking::begin_panic<alloc::string::String>
             at C:\projects\rust\src\libstd\panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:522
   7: std::panicking::rust_begin_panic
             at C:\projects\rust\src\libstd\panicking.rs:498
   8: core::panicking::panic_fmt
             at C:\projects\rust\src\libcore\panicking.rs:71
   9: core::result::unwrap_failed<shred::cell::InvalidBorrow>
             at C:\projects\rust\src\libcore\macros.rs:23
  10: core::result::Result::expect<(),shred::cell::InvalidBorrow>
             at C:\projects\rust\src\libcore\result.rs:809
  11: shred::cell::TrustCell<alloc::boxed::Box<Resource>>::borrow_mut<alloc::boxed::Box<Resource>>
             at C:\Users\Jed Irvine\.cargo\registry\src\github.com-1ecc6299db9ec823\shred-0.5.2\src\cell.rs:95
  12: shred::res::{{impl}}::try_fetch_mut::{{closure}}<specs::storage::MaskedStorage<backend::engine::components::move_component::Movable>>
             at C:\Users\Jed Irvine\.cargo\registry\src\github.com-1ecc6299db9ec823\shred-0.5.2\src\res\mod.rs:348
  13: core::option::Option<shred::cell::TrustCell<alloc::boxed::Box<Resource>>*>::map<shred::cell::TrustCell<alloc::boxed::Box<Resource>>*,shred::res::FetchMut<specs::storage::MaskedStorage<backend::engine::components::move_component::Movable>>,closure>
             at C:\projects\rust\src\libcore\option.rs:404
  14: shred::res::Resources::try_fetch_mut<specs::storage::MaskedStorage<backend::engine::components::move_component::Movable>>
             at C:\Users\Jed Irvine\.cargo\registry\src\github.com-1ecc6299db9ec823\shred-0.5.2\src\res\mod.rs:346
  15: shred::res::Resources::fetch_mut<specs::storage::MaskedStorage<backend::engine::components::move_component::Movable>>
             at C:\Users\Jed Irvine\.cargo\registry\src\github.com-1ecc6299db9ec823\shred-0.5.2\src\res\mod.rs:337
  16: specs::storage::data::{{impl}}::fetch<backend::engine::components::move_component::Movable>
             at C:\Users\Jed Irvine\.cargo\git\checkouts\specs-c79cf5e81a2b73c9\30ed057\src\storage\data.rs:201
  17: shred::system::impl_data::{{impl}}::fetch<specs::storage::Storage<backend::engine::components::move_component::Speed, shred::res::FetchMut<specs::storage::MaskedStorage<backend::engine::components::move_component::Speed>>>,specs::storage::Storage<backend::engine::components::move_component::Movable, shred::res::FetchMut<specs::storage::MaskedStorage<backend::engine::components::move_component::Movable>>>,specs::storage::Storage<backend::engine::components::move_component::Static, shred::res::FetchMut<specs::storage::MaskedStorage<backend::engine::components::move_component::Static>>>,specs::storage::Storage<backend::engine::components::move_component::Move, shred::res::FetchMut<specs::storage::MaskedStorage<backend::engine::components::move_component::Move>>>,specs::storage::Storage<backend::engine::components::Pos, shred::res::FetchMut<specs::storage::MaskedStorage<backend::engine::components::Pos>>>,specs::storage::Storage<backend::engine::components::MovedFlag, shred::res::FetchMut<specs::storage::MaskedStorage<backend::engine::components::MovedFlag>>>,specs::storage::Storage<backend::engine::components::move_component::Movable, shred::res::FetchMut<specs::storage::MaskedStorage<backend::engine::components::move_component::Movable>>>,specs::storage::Storage<backend::engine::components::Hp, shred::res::FetchMut<specs::storage::MaskedStorage<backend::engine::components::Hp>>>,specs::storage::Storage<backend::engine::components::Color, shred::res::FetchMut<specs::storage::MaskedStorage<backend::engine::components::Color>>>,specs::storage::Storage<backend::engine::components::Shape, shred::res::FetchMut<specs::storage::MaskedStorage<backend::engine::components::Shape>>>,specs::storage::Storage<backend::engine::components::FactionId, shred::res::FetchMut<specs::storage::MaskedStorage<backend::engine::components::FactionId>>>,specs::storage::Storage<backend::engine::components::Attack, shred::res::FetchMut<specs::storage::MaskedStorage<backend::engine::components::Atta
             at C:\Users\Jed Irvine\.cargo\registry\src\github.com-1ecc6299db9ec823\shred-0.5.2\src\system.rs:135
  18: specs::saveload::de::{{impl}}::fetch<specs::saveload::marker::U64Marker,specs::error::NoError,(backend::engine::components::move_component::Speed, backend::engine::components::move_component::Movable, backend::engine::components::move_component::Static, backend::engine::components::move_component::Move, backend::engine::components::Pos, backend::engine::components::MovedFlag, backend::engine::components::move_component::Movable, backend::engine::components::Hp, backend::engine::components::Color, backend::engine::components::Shape, backend::engine::components::FactionId, backend::engine::components::Attack, backend::engine::components::UnitTypeTag)>
             at C:\Users\Jed Irvine\.cargo\git\checkouts\specs-c79cf5e81a2b73c9\30ed057\src\saveload\de.rs:119
  19: backend::engine::systems::serde::de::{{impl}}::fetch
             at C:\Users\Jed Irvine\.scaii\git\Sky-RTS\backend\src\engine\systems\serde\de.rs:14
  20: shred::system::{{impl}}::run_now<backend::engine::systems::serde::de::DeserializeSystem>
             at C:\Users\Jed Irvine\.cargo\registry\src\github.com-1ecc6299db9ec823\shred-0.5.2\src\system.rs:23
  21: backend::engine::Rts::deserialize
             at C:\Users\Jed Irvine\.scaii\git\Sky-RTS\backend\src\engine\mod.rs:473
  22: backend::{{impl}}::deserialize
             at C:\Users\Jed Irvine\.scaii\git\Sky-RTS\backend\src\lib.rs:262
```

**Comment by UserAB1236872** [comment]
This is a specs bug, I'm gonna have to bite the bullet and upgrade it.

**Comment by jedirv** [comment]
Got past that error but hit another. 

```
%%%%%%%%%%%%%   Replay sending action_pkt with ser_response  %%%%%%%%%%%%%%
received packet ScaiiPacket { src: Endpoint { endpoint: Some(Replay(ReplayEndpoint)) }, 
          dest: Endpoint { endpoint: Some(Backend(BackendEndpoint)) }, specific_msg: Some(SerResp(SerializationResponse 
		  { serialized: [163, 106,  117, 115,...<lots of bytes> .... 101, 100, 244], format: 1 })) }

thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorImpl { code: Message("invalid type: sequence, expected unit struct MovedFlag"), offset: 0 }', src\libcore\result.rs:916:5
stack backtrace:
   0: std::sys::windows::backtrace::unwind_backtrace
             at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:65
   1: std::sys_common::backtrace::print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:56
   2: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:381
   3: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:577
   5: std::panicking::begin_panic<alloc::string::String>
             at C:\projects\rust\src\libstd\panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:522
   7: std::panicking::rust_begin_panic
             at C:\projects\rust\src\libstd\panicking.rs:498
   8: core::panicking::panic_fmt
             at C:\projects\rust\src\libcore\panicking.rs:71
   9: core::result::unwrap_failed<serde_cbor::error::Error>
             at C:\projects\rust\src\libcore\macros.rs:23
  10: core::result::Result<(), serde_cbor::error::Error>::unwrap<(),serde_cbor::error::Error>
             at C:\projects\rust\src\libcore\result.rs:782
  11: backend::engine::systems::serde::de::{{impl}}::run
             at C:\Users\Jed Irvine\.scaii\git\Sky-RTS\backend\src\engine\systems\serde\de.rs:60
  12: shred::system::{{impl}}::run_now<backend::engine::systems::serde::de::DeserializeSystem>
             at C:\Users\Jed Irvine\.cargo\registry\src\github.com-1ecc6299db9ec823\shred-0.5.2\src\system.rs:24
  13: backend::engine::Rts::deserialize
             at C:\Users\Jed Irvine\.scaii\git\Sky-RTS\backend\src\engine\mod.rs:473
  14: backend::{{impl}}::deserialize
             at C:\Users\Jed Irvine\.scaii\git\Sky-RTS\backend\src\lib.rs:262
  15: backend::Context::handle_de
             at C:\Users\Jed Irvine\.scaii\git\Sky-RTS\backend\src\lib.rs:177
  16: backend::{{impl}}::process_msg
             at C:\Users\Jed Irvine\.scaii\git\Sky-RTS\backend\src\lib.rs:238
  17: scaii_core::internal::rust_ffi::{{impl}}::process_msg
             at .\src\internal\rust_ffi.rs:83
  18: scaii_core::internal::router::{{impl}}::route_to::{{closure}}
             at .\src\internal\router.rs:136
  19: core::option::Option<mut alloc::boxed::Box<Backend>*>::and_then<mut alloc::boxed::Box<Backend>*,core::result::Result<(), alloc::boxed::Box<Error>>,closure>
             at C:\projects\rust\src\libcore\option.rs:616
  20: scaii_core::internal::router::Router::route_to
             at .\src\internal\router.rs:136
  21: scaii_core::internal::router::Router::decode_and_route
             at .\src\internal\router.rs:114
  22: scaii_core::Environment::route_messages
             at .\src\lib.rs:78
  23: replay::ReplayManager::deploy_replay_directives_to_backend
             at .\src\internal\replay\main.rs:428
  24: replay::ReplayManager::send_replay_action_to_backend
             at .\src\internal\replay\main.rs:469
  25: replay::ReplayManager::execute_run_step
             at .\src\internal\replay\main.rs:548
  26: replay::ReplayManager::handle_step_nudge
             at .\src\internal\replay\main.rs:769
  27: replay::ReplayManager::run_and_poll
             at .\src\internal\replay\main.rs:745
  28: replay::ReplayManager::start
             at .\src\internal\replay\main.rs:156
  29: replay::run_replay
             at .\src\internal\replay\main.rs:1075
  30: replay::main
             at .\src\internal\replay\main.rs:1033
  31: std::rt::lang_start::{{closure}}<()>
             at C:\projects\rust\src\libstd\rt.rs:74
  32: std::panicking::try::do_call<closure,i32>
             at C:\projects\rust\src\libstd\panicking.rs:476
  33: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:101
  34: std::rt::lang_start_internal
             at C:\projects\rust\src\libstd\rt.rs:50
  35: std::rt::lang_start<()>
             at C:\projects\rust\src\libstd\rt.rs:74
  36: main
  37: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:259
  38: BaseThreadInitThunk
thread 'thread '<unnamed><unnamed>' panicked at '' panicked at 'called `Result::unwrap()` on an `Err` value: RecvErrorcalled `Result::unwrap()` on an `Err` value: RecvError', ', src\libcore\result.rssrc\libcore\result.rs::916916::5error: process didn't exit successfully: `C:\Users\Jed Irvine\.scaii\git\SCAII\target\debug\replay.exe file` (exit code: 101)

(C:\Users\Jed Irvine\Anaconda3) C:\Users\Jed Irvine\.scaii\git\SCAII\core>
```

**Comment by jedirv** [comment]
I'll need to commit some stuff for you to replicate

**Comment by jedirv** [comment]
ok, you can replicate with the process outlined in the original issue text.  Let me know when get past the errors or errors emitting from my side of fence.
